# Generated by Django 4.0.4 on 2022-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('startYear', models.PositiveSmallIntegerField()),
                ('endYear', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('workplace', models.CharField(max_length=50)),
                ('startYear', models.PositiveSmallIntegerField()),
                ('endYear', models.PositiveSmallIntegerField()),
                ('responsibilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('proficiency', models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Regular'), (3, 'Expert')], default=2)),
            ],
        ),
    ]
